version: '3'

services:
  fitnesshelper:
    build: .
    image: fitnesshelper
    container_name: fitnesshelper1
    depends_on:
      - redis
    ports:
      - 3306:3306
    volumes:
      - type: bind
        source: ./config/server.env
        target: /myapp/server/.env
      - type: bind
        source: ./config/frontend.env
        target: /myapp/frontend/.env
      - type: bind
        source: ./ssl
        target: /myapp/ssl
    networks:
      - net1
  redis:
    image: redis
    container_name: redis1
    networks:
      - net1
  nginx:
    image: nginx
    container_name: nginx1
    depends_on:
      - fitnesshelper
    ports:
      - 443:443
    volumes:
      - type : bind
        source : ./ssl
        target : /etc/ssl/fitnesshelper
      - type : bind
        source : ./config/nginx.conf
        target : /etc/nginx/conf.d/default.conf
    networks:
      - net1

networks:
  net1: